# Generator params
CONFIG_SPACE = 'config_space'
EXPERIMENT = 'experiment'
GENERATOR_PARAMS = 'generator_params'
N_TRIALS = 'n_trials'
PLOT_REFERENCE_FEATURE = 'plot_reference_feature'
SIMILARITY_THRESHOLD = 'similarity_threshold'
LOGS_SAVE_PATH = 'logs_save_path'
TARGET_SIMILARITY = 'target_similarity'
METAFEATURES = 'metafeatures'
FEATURES = 'features'
LOG = 'log'
FEATURE_KEYS='feature_keys'
