name: SHAining Test

# Specifies when the action should run
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Specifies the jobs that are to be run
jobs:
  test_benchmark:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &

    - name: Set DISPLAY variable
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        pytest -v tests/test_benchmark.py --maxfail=1 --disable-warnings -q

  test_benchmark_system_thresholds:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &

    - name: Set DISPLAY variable
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        pytest -v tests/test_benchmark_system_thresholds.py --maxfail=1 --disable-warnings -q

  test_generation:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &

    - name: Set DISPLAY variable
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        pytest -v tests/test_generator.py --maxfail=1 --disable-warnings -q

  test_generation_skipping_duplicates:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &

    - name: Set DISPLAY variable
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run test for duplicates
      run:
        pytest -v tests/test_generator_check_duplicate.py --maxfail=1 --disable-warnings -q

  test_generation_check_naming_scheme:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &

    - name: Set DISPLAY variable
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run test for checking naming scheme
      run:
        pytest -v tests/test_generator_check_naming_scheme.py --maxfail=1 --disable-warnings -q

  test_compute_similarity_posterously:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &

    - name: Set DISPLAY variable
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test for duplicates
      run: python main.py -a config_files/test/generation.json

    - name: Run test for similarity computation
      run: python -m shaining.utils.compute_similarity_posteriously output/triangle_gen/test/3_nt_rvpnot_tlm config_files/test/generation.json 0.7

  test_shapley:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &

    - name: Set DISPLAY variable
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test for calculating shapely values
      run:
        pytest -v tests/test_shapley.py --maxfail=1 --disable-warnings -q

  test_coalitions:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x16 &

    - name: Set DISPLAY variable
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test for calculating coalitions
      run:
        pytest -v tests/test_coalitions.py --maxfail=1 --disable-warnings -q
